### ISSUE TITLE
 Error converting value "phone" to type 'Meraki.Api.Data.ProductType'

### ISSUE THREAD

**Issue by blaherrod** [panoramicdata/Meraki.Api#2]
this is the error 

Unhandled exception. Refit.ApiException: An error occured deserializing the response.
 ---> Newtonsoft.Json.JsonSerializationException: Error converting value "phone" to type 'Meraki.Api.Data.ProductType'. Path '[0].productType', line 1, position 226.
 ---> System.ArgumentException: Requested value 'phone' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Refit.NewtonsoftJsonContentSerializer.FromHttpContentAsync[T](HttpContent content, CancellationToken cancellationToken) in /_/Refit.Newtonsoft.Json/NewtonsoftJsonContentSerializer.cs:line 56
   at Refit.RequestBuilderImplementation.DeserializeContentAsync[T](HttpResponseMessage resp, HttpContent content, CancellationToken cancellationToken) in /_/Refit/RequestBuilderImplementation.cs:line 344
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 294
   --- End of inner exception stack trace ---
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at TestMerakiDashboard.Program.Main(String[] args) in D:\source\Repos\Personal\TestMerakiDashboard\TestMerakiDashboard\TestMerakiDashboard\Program.cs:line 31
   at TestMerakiDashboard.Program.<Main>(String[] args)

Response from API, testing  from 
https://developer.cisco.com/meraki/api-v1/#!get-organization-inventory-devices
[
    {
        "mac": "e0:55:3d:4f:fd:90",
        "serial": "Q2AT-4UEN-MUS7",
        "name": null,
        "model": "MC74",
        "networkId": null,
        "orderNumber": "5C8249945",
        "claimedAt": "2017-10-31T15:20:38.735291Z",
        "licenseExpirationDate": null,
        "tags": [],
        "productType": "phone"
    },
    {
        "mac": "e0:55:3d:4f:1b:1f",
        "serial": "Q2AT-6CC4-J9EK",
        "name": "",
        "model": "MC74",
        "networkId": null,
        "orderNumber": "5C8249945",
        "claimedAt": "2017-10-31T15:20:38.768314Z",
        "licenseExpirationDate": null,
        "tags": [],
        "productType": "phone"
    },
    {
        "mac": "e0:55:3d:4f:fc:8e",
        "serial": "Q2AT-FMB2-VZ32",
        "name": null,
        "model": "MC74",
        "networkId": null,
        "orderNumber": "5C8249945",
        "claimedAt": "2017-10-31T15:20:38.778014Z",
        "licenseExpirationDate": null,
        "tags": [],
        "productType": "phone"
    },
    {
        "mac": "e0:55:3d:50:01:6b",
        "serial": "Q2AT-M8BM-YZTC",
        "name": null,
        "model": "MC74",
        "networkId": null,
        "orderNumber": "5C8249945",
        "claimedAt": "2017-10-31T15:20:38.786043Z",
        "licenseExpirationDate": null,
        "tags": [],
        "productType": "phone"
    },
    {
        "mac": "0c:8d:db:95:8f:a3",
        "serial": "Q2BV-HGZ7-WDK6",
        "name": null,
        "model": "MV21",
        "networkId": null,
        "orderNumber": "5C8249945",
        "claimedAt": "2017-10-31T15:20:38.853422Z",
        "licenseExpirationDate": null,
        "tags": [],
        "productType": "camera"
    }
...
]

**Comment by danielabbatt** [comment]
Sorry for the late response, yes it does indeed look like this should be added to the enum, we're confirming with Meraki that "phone" should be added to their documentation as valid productType.

**Comment by danielabbatt** [comment]
We've reviewed this with Meraki and actually 'phone' isn't supported by the API any more and so is out of scope for this library. You could fork and merge that change in for your own use if required though.

**Comment by iansmith-ggr** [comment]
@danielabbatt  Sorry for reviving this issue, but I have got this same error today working against Meraki's sandbox data. Has the 'phone' product type been brought back into scope? If not is there a way to avoid the exception that is caused?
