### ISSUE TITLE
Bad Request to call SM devices with additional fields

### ISSUE THREAD

**Issue by blaherrod** [panoramicdata/Meraki.Api#4]
I am making the following call to the service to get SM devices
`string additionalFields = "ip,systemType";
	try
	{
		var devicesNetwork = await merakiClient.Sm.Devices.GetNetworkSmDevicesAsync(
																		networkId: NetWorkSystemManager.Id, 
																		fields: additionalFields,
																		batchSize:1000).ConfigureAwait(false);
NetWorkSystemManager.Id).ConfigureAwait(false);

		Console.WriteLine("Devices network:");
		foreach (var device in devicesNetwork)
		{
			Console.WriteLine($"    - {device.Serial}: {device.Name}");
		}
	}catch(Exception ex)
	{
		Console.WriteLine(ex.Message);
	}`

the application throw the next exception:
"Response status code does not indicate success: 400 (Bad Request)."

the service response:
{"errors":["'fields' must be an array"]}

this is the url : 
https://api.meraki.com/api/v1/networks/N_000000000000/sm/devices?fields=ip%2CsystemType&batchSize=1000

stacktrace:
at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 288
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TestMerakiDashboard.Program.<Main>d__0.MoveNext() in D:\source\Repos\Personal\TestMerakiDashboard\TestMerakiDashboard\TestMerakiDashboard\Program.cs:line 50

with this url it works, using curl call:

https://api.meraki.com/api/v1/networks/N_000000000000/sm/devices?fields%5B%5D=ip&fields%5B%5D=systemType&perPage=1000&startingAfter=713820540938246263

thanks!

**Comment by danielabbatt** [comment]
This should be fixed by pull request #5
